name: "Build and Push service"
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
    tags:
      - v*

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build-service:
    name: "Build service"
    uses: ./.github/workflows/build.yaml
    with:
      service: user
      push: ${{ github.event_name != 'pull_request' }}
      docker_repository: service
      dockerfile: "./build/package/Dockerfile"

